node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    withSonarQubeEnv() {
      dir('./backend/da_ta/') {
        sh "chmod +x ./gradlew"
        sh "./gradlew sonarqube"
      }
    }
  }
}